version: '3'

services:
  mysql:
    container_name: mysql        # 指定容器的名称
    image: mysql     # 指定镜像和版本
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=test_db
    restart: always